### ISSUE TITLE
The training process on custom data dies, what to do?

### ISSUE THREAD

**Issue by MykytaKyt** [ashawkey/torch-ngp#131]
Versions:
Ubuntu 18.04
Cuda 11.2
Torch 1.11
I prepared data with COLMAP and started training on the custom dataset, dataloader loads data and its interrupts (seem's like I kill the process but I didn't press any button). Also, I tried on the Fox dataset, and everything works, but on custom, it dies, how fix it?
![IMAGE 2022-11-19 00:49:50](https://user-images.githubusercontent.com/59031709/202816007-b799a8ea-528e-46cb-9498-b7c84b8aa036.jpg)

I tried it on wsl2 with Ubuntu 22.04, CUDA 11.3, Torch 1.12 and the situation is about the same. I installed all dependencies and built raytracing. On the fox dataset everything ok, but on my custom, it loads data and then prints "KILLED". 
About the dataset it contains 325 images with 1080p resolution, I tested it on Nvidia instant-ngp, and it worked fine. Help please

**Comment by castoner** [comment]
Hello, i have meet same problem.would you solved this issue?

**Comment by MykytaKyt** [comment]
> Hello, i have meet same problem.would you solved this issue?

Not yet, how about you?

**Comment by arbab-isu** [comment]
It is because of out of memory issue of your GPU. 
You can use the command **dmesg** to confirm it.   
Solution: 
Downscale the your images. 
Line 133 in main_nerf.py. Update the dataloader line as follows:      
train_loader = NeRFDataset(opt, device=device, type='train', downscale=16).dataloader()
Please not that I have added downscale=16. You might want to adjust it. 16 will downsample it by a lot. Hence fitting it in memory.
