### ISSUE TITLE
Nerf-synthetic and LLFF training

### ISSUE THREAD

**Issue by phongnhhn92** [ashawkey/torch-ngp#15]
Hello,

Thanks for the great code! I have tried your code with fox scene and it works perfectly. However, I receive this error for the chair scene of NeRF. It seems like in the transforms_train file I need to declare a bunch of additional stuff that I found in the transforms.json of the fox scene. How did you use your code to train on NeRF and LLFF datasets?

```
python gui_nerf.py data/nerf_synthetic/chair/transforms_train.json --workspace trial_nerf --fp16 --ff --cuda_ray --train
Traceback (most recent call last):
  File "gui_nerf.py", line 361, in <module>
    train_dataset = NeRFDataset(opt.path, 'train', radius=opt.radius)
  File "/home/phong/data/Work/Paper_journal/torch-ngp/nerf/provider.py", line 47, in __init__
    self.H = int(transform['h']) // downscale
KeyError: 'h'
```
![image](https://user-images.githubusercontent.com/11288381/155164661-8bec2fdc-4ef3-46ab-9599-e2f0e4d4ad72.png)

**Comment by ashawkey** [comment]
@phongnhhn92 Hi, I just added better support for the blender dataset, you can follow the new readme to try. I'll start work on LLFF later.

**Comment by ashawkey** [comment]
LLFF format is too different, and since instant-ngp also doesn't support it, I give up supporting it for now... 
You may implement it by yourself if you really need it.

**Comment by phongnhhn92** [comment]
Thanks @ashawkey ! I will try to do it. Can you point out what are the difficulties that you have with LLFF so I can work on it.

**Comment by ashawkey** [comment]
Well, the main problem is the different format of camera poses. There are two choices of doing this:
* write a script to transform the llff poses_bounds.npy into nerf-compatible json file, and load through the `NeRFDataset` class.
* implement a new class, such as in [nerf_pl](https://github.com/kwea123/nerf_pl/blob/master/datasets/llff.py).

since I want (am) to (too) keep the code simple (lazy), I am not planning to add another dataloader class now...
