### ISSUE TITLE
question about the camera->world: c2w transpose and world->camera: c2w transpose.

### ISSUE THREAD

**Issue by neilgogogo** [ashawkey/torch-ngp#58]
hi, thank you for your excellent work.

I have one question about the pose.

In get_rays function, the directions of the camera coordinates, times the transpose of c2w, to get the world coordinates direction.
https://github.com/ashawkey/torch-ngp/blob/23583b10d5353d96ec0f5800eac786728557f767/nerf/utils.py#L92-L96

While in the mark_untrained_density function, the world coordinate point, times the transpose of c2w, to get the camera coordinate position.
https://github.com/ashawkey/torch-ngp/blob/23583b10d5353d96ec0f5800eac786728557f767/nerf/renderer.py#L386-L389

It is kinda weird that the camera->world: c2w transpose
                                          world->camera: c2w transpose.

Many thanks

Neil

**Comment by ashawkey** [comment]
Thanks for spotting the bug! The first needs transpose for batched matmul, and the second pose in `mark_untrained_density` should not be transposed, since the two tranposes (c2w -> w2c, and another one for batch matmul) should cancel each other. However, this wrong piece of code somewhat still works similarly.
This will be fixed soon.

**Comment by ashawkey** [comment]
fixed in https://github.com/ashawkey/torch-ngp/commit/ad5626340eddf7fb74091b78ebcb5a2ea81fb607
