### ISSUE TITLE
Why is output dims limited to 16?

### ISSUE THREAD

**Issue by rohitrango** [ashawkey/torch-ngp#68]
Hi ashawkey,

Thank you for the amazing work. I have a small question. In the FFMLP's `__init__` function, there is this line of code:
```
        assert output_dim <= 16, f"FFMLP current only supports output dim <= 16, but got {output_dim}"
```

Why is the output_dim limited to 16? The corresponding CUDA code doesn't seem to have this constraint (or maybe I missed it). In any case, thanks in advance for clarifying!

**Comment by ashawkey** [comment]
@rohitrango Hi, although the original code from instant-ngp seems to support output dim > 16, I haven't tested the correctness of it. You could first test with `--tcnn` if necessary. 
BTW, I recommend to simply use the pytorch native MLPs, since they have very similar performance but are more general and easy-to-use.

**Comment by ashawkey** [comment]
That is strange though, FP16 should still work before that commit. If you still meet problems, welcome to report!
